### ISSUE TITLE
Codescanner not working in iPadOS 17.4

### ISSUE THREAD

**Issue by BSDOezdemir** [twostraws/CodeScanner#134] opened 2024-03-08 12:50 UTC
Since the iOS 17.4 Update, CodeScannerView doesn't seem to call the closure when trying to scan codes. Issue has been seen with the newest version of CodeScanner 2.4. Tested on an iPad 6th generation with iOS 17.4. Worked fine before the 17.4 Update.

**Comment by BSDOezdemir** [comment] 2024-03-08 14:09
I went a bit further into this, and this is what I found:

On an iPad, the function metadataOutput is not called by the AVFoundation framework. Therefore I believe this is an issue with AVFoundation, rather than this library. Especially since the same Code works on an iPhone, this could be an internal problem in AVFoundation on certain devices.

**Comment by david-hosier** [comment] 2024-03-21 20:02
@BSDOezdemir  I just saw this article that mentions what is likely the cause of your trouble. https://www.macrumors.com/2024/03/21/ios-17-4-1-qr-code-scanning-bug/

**Comment by nathanfallet** [comment] 2024-03-22 20:51
@BSDOezdemir This should be fixed in iPadOS 17.4.1. Please reopen if you still experience an issue.

**Closed by nathanfallet** 2024-03-22 20:51 UTC
