### ISSUE TITLE
Simulator not working with barcodes

### ISSUE THREAD

**Issue by nikitaskobelkin** [twostraws/CodeScanner#63] opened 2022-04-02 15:50 UTC
1. Open scan on the simulator (Xcode)
2. Scan from photo
3. Choose barcode (for example code128 and etc.)
4. Failure response

But on the real device is ok.

**Comment by kassi** [comment] 2022-07-31 00:46
Same issue for me with QR codes.

I'm using it in the HotProspects project from the course and it is unable to scan the images it has saved.
Output is:
```
HotProspects[28896:3017418] Cannot find executable for CFBundle 0x12a372bb0 </System/Library/PrivateFrameworks/Quagga.framework> (not loaded)
Unable to load Quagga from /System/Library/PrivateFrameworks/Quagga.framework
Scanning failed: The operation couldn’t be completed. (CodeScanner.ScanError error 2.)
```

**Comment by NathanFallet** [comment] 2022-08-28 15:32
@nikitaskobelkin @kassi Is the bug still present in the latest version?

**Comment by kassi** [comment] 2022-08-29 10:11
@nikitaskobelkin just tried again and can't reproduce. As I wrote already, restarting the simulator helped. Didn't have the problem this time.

**Comment by NathanFallet** [comment] 2022-08-29 10:25
Well, closing as the issue is not here anymore for now. If it occurs again, please reopen.

Also note that simulator scanning is not done the same way as real scanning from camera: https://github.com/twostraws/CodeScanner/blob/9aef09bf5c0274689a89c2fd71794011bebdc43f/Sources/CodeScanner/ScannerViewController.swift#L58

**Closed by NathanFallet** 2022-08-29 10:25 UTC
Labels: bug
